// Lightweight emoji dataset (subset) with names/keywords for basic search/filter.
// If you want a fully exhaustive Unicode emoji list later, we can swap this for a generated dataset or a library.

export const EMOJI_CATEGORIES = [
  { key: 'all', label: 'All' },
  { key: 'frequent', label: 'Frequent' },
  { key: 'custom', label: 'Custom' },
  { key: 'smileys', label: 'Smileys' },
  { key: 'people', label: 'People' },
  { key: 'animals', label: 'Animals' },
  { key: 'food', label: 'Food' },
  { key: 'activities', label: 'Activities' },
  { key: 'travel', label: 'Travel' },
  { key: 'objects', label: 'Objects' },
  { key: 'symbols', label: 'Symbols' },
  { key: 'flags', label: 'Flags' }
];

export const DEFAULT_FAVORITES = [
  '👍', '❤️', '😂', '🔥', '🙏', '🎉', '🥳', '😄', '😅', '😉', '🤝', '✅', '🚀', '💯', '👀', '🤔'
];

/** @type {{emoji: string, name: string, keywords: string[], category: string}[]} */
export const EMOJI_LIST = [
  // Smileys & Emotion
  { emoji: '😀', name: 'grinning face', keywords: ['smile', 'happy'], category: 'smileys' },
  { emoji: '😃', name: 'grinning face with big eyes', keywords: ['smile', 'happy'], category: 'smileys' },
  { emoji: '😄', name: 'grinning face with smiling eyes', keywords: ['smile', 'happy', 'laugh'], category: 'smileys' },
  { emoji: '😁', name: 'beaming face with smiling eyes', keywords: ['grin', 'happy'], category: 'smileys' },
  { emoji: '😆', name: 'grinning squinting face', keywords: ['laugh', 'lol'], category: 'smileys' },
  { emoji: '😅', name: 'grinning face with sweat', keywords: ['relief', 'nervous'], category: 'smileys' },
  { emoji: '🤣', name: 'rolling on the floor laughing', keywords: ['rofl', 'lol', 'laugh'], category: 'smileys' },
  { emoji: '😂', name: 'face with tears of joy', keywords: ['lol', 'laugh'], category: 'smileys' },
  { emoji: '🙂', name: 'slightly smiling face', keywords: ['smile'], category: 'smileys' },
  { emoji: '😉', name: 'winking face', keywords: ['wink'], category: 'smileys' },
  { emoji: '😊', name: 'smiling face with smiling eyes', keywords: ['blush', 'happy'], category: 'smileys' },
  { emoji: '😇', name: 'smiling face with halo', keywords: ['angel'], category: 'smileys' },
  { emoji: '🥰', name: 'smiling face with hearts', keywords: ['love', 'adorable'], category: 'smileys' },
  { emoji: '😍', name: 'smiling face with heart-eyes', keywords: ['love', 'crush'], category: 'smileys' },
  { emoji: '🤩', name: 'star-struck', keywords: ['wow', 'excited'], category: 'smileys' },
  { emoji: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love'], category: 'smileys' },
  { emoji: '😗', name: 'kissing face', keywords: ['kiss'], category: 'smileys' },
  { emoji: '😚', name: 'kissing face with closed eyes', keywords: ['kiss'], category: 'smileys' },
  { emoji: '😙', name: 'kissing face with smiling eyes', keywords: ['kiss'], category: 'smileys' },
  { emoji: '😋', name: 'face savoring food', keywords: ['yum', 'delicious'], category: 'smileys' },
  { emoji: '😜', name: 'winking face with tongue', keywords: ['joke', 'playful'], category: 'smileys' },
  { emoji: '🤪', name: 'zany face', keywords: ['crazy', 'silly'], category: 'smileys' },
  { emoji: '😝', name: 'squinting face with tongue', keywords: ['silly'], category: 'smileys' },
  { emoji: '🤑', name: 'money-mouth face', keywords: ['rich', 'money'], category: 'smileys' },
  { emoji: '🤗', name: 'hugging face', keywords: ['hug'], category: 'smileys' },
  { emoji: '🤭', name: 'face with hand over mouth', keywords: ['oops', 'giggle'], category: 'smileys' },
  { emoji: '🤫', name: 'shushing face', keywords: ['quiet', 'shh'], category: 'smileys' },
  { emoji: '🤔', name: 'thinking face', keywords: ['think', 'hmm'], category: 'smileys' },
  { emoji: '🤐', name: 'zipper-mouth face', keywords: ['secret'], category: 'smileys' },
  { emoji: '🤨', name: 'face with raised eyebrow', keywords: ['skeptic', 'hmm'], category: 'smileys' },
  { emoji: '😐', name: 'neutral face', keywords: ['meh'], category: 'smileys' },
  { emoji: '😑', name: 'expressionless face', keywords: ['blank'], category: 'smileys' },
  { emoji: '😶', name: 'face without mouth', keywords: ['silent'], category: 'smileys' },
  { emoji: '🫠', name: 'melting face', keywords: ['tired', 'heat'], category: 'smileys' },
  { emoji: '🙄', name: 'face with rolling eyes', keywords: ['eyeroll'], category: 'smileys' },
  { emoji: '😏', name: 'smirking face', keywords: ['smirk'], category: 'smileys' },
  { emoji: '😣', name: 'persevering face', keywords: ['struggle'], category: 'smileys' },
  { emoji: '😥', name: 'sad but relieved face', keywords: ['relief', 'sad'], category: 'smileys' },
  { emoji: '😮', name: 'face with open mouth', keywords: ['surprise'], category: 'smileys' },
  { emoji: '🤯', name: 'exploding head', keywords: ['mindblown', 'wow'], category: 'smileys' },
  { emoji: '😪', name: 'sleepy face', keywords: ['tired'], category: 'smileys' },
  { emoji: '😴', name: 'sleeping face', keywords: ['sleep'], category: 'smileys' },
  { emoji: '😵', name: 'dizzy face', keywords: ['dizzy'], category: 'smileys' },
  { emoji: '🤕', name: 'face with head-bandage', keywords: ['hurt', 'injury'], category: 'smileys' },
  { emoji: '🤒', name: 'face with thermometer', keywords: ['sick', 'fever'], category: 'smileys' },
  { emoji: '🤢', name: 'nauseated face', keywords: ['sick'], category: 'smileys' },
  { emoji: '🤮', name: 'face vomiting', keywords: ['sick'], category: 'smileys' },
  { emoji: '🥵', name: 'hot face', keywords: ['hot'], category: 'smileys' },
  { emoji: '🥶', name: 'cold face', keywords: ['cold'], category: 'smileys' },
  { emoji: '😡', name: 'pouting face', keywords: ['angry'], category: 'smileys' },
  { emoji: '😠', name: 'angry face', keywords: ['angry'], category: 'smileys' },
  { emoji: '😤', name: 'face with steam from nose', keywords: ['frustrated'], category: 'smileys' },
  { emoji: '😭', name: 'loudly crying face', keywords: ['sad', 'cry'], category: 'smileys' },
  { emoji: '😢', name: 'crying face', keywords: ['sad', 'cry'], category: 'smileys' },
  { emoji: '😞', name: 'disappointed face', keywords: ['sad'], category: 'smileys' },
  { emoji: '😓', name: 'downcast face with sweat', keywords: ['sad', 'sweat'], category: 'smileys' },
  { emoji: '😱', name: 'face screaming in fear', keywords: ['scared'], category: 'smileys' },
  { emoji: '😳', name: 'flushed face', keywords: ['embarrassed'], category: 'smileys' },
  { emoji: '🥺', name: 'pleading face', keywords: ['please'], category: 'smileys' },
  { emoji: '😬', name: 'grimacing face', keywords: ['awkward'], category: 'smileys' },
  { emoji: '😎', name: 'smiling face with sunglasses', keywords: ['cool'], category: 'smileys' },
  { emoji: '🤓', name: 'nerd face', keywords: ['nerd'], category: 'smileys' },
  { emoji: '🧐', name: 'face with monocle', keywords: ['inspect'], category: 'smileys' },
  { emoji: '😈', name: 'smiling face with horns', keywords: ['devil'], category: 'smileys' },
  { emoji: '👿', name: 'angry face with horns', keywords: ['devil'], category: 'smileys' },
  { emoji: '💀', name: 'skull', keywords: ['dead'], category: 'smileys' },
  { emoji: '☠️', name: 'skull and crossbones', keywords: ['danger'], category: 'smileys' },
  { emoji: '🤡', name: 'clown face', keywords: ['clown'], category: 'smileys' },
  { emoji: '👻', name: 'ghost', keywords: ['spooky'], category: 'smileys' },
  { emoji: '👽', name: 'alien', keywords: ['ufo'], category: 'smileys' },
  { emoji: '🤖', name: 'robot', keywords: ['bot'], category: 'smileys' },

  // People & Body
  { emoji: '👍', name: 'thumbs up', keywords: ['like', 'yes', 'approve'], category: 'people' },
  { emoji: '👎', name: 'thumbs down', keywords: ['dislike', 'no'], category: 'people' },
  { emoji: '👏', name: 'clapping hands', keywords: ['clap', 'applause'], category: 'people' },
  { emoji: '🙌', name: 'raising hands', keywords: ['hooray', 'celebrate'], category: 'people' },
  { emoji: '🫶', name: 'heart hands', keywords: ['love'], category: 'people' },
  { emoji: '🙏', name: 'folded hands', keywords: ['pray', 'thanks', 'please'], category: 'people' },
  { emoji: '🤝', name: 'handshake', keywords: ['deal', 'agree'], category: 'people' },
  { emoji: '💪', name: 'flexed biceps', keywords: ['strong', 'workout'], category: 'people' },
  { emoji: '✍️', name: 'writing hand', keywords: ['write'], category: 'people' },
  { emoji: '👀', name: 'eyes', keywords: ['look', 'see'], category: 'people' },
  { emoji: '👋', name: 'waving hand', keywords: ['hello', 'bye'], category: 'people' },
  { emoji: '🤞', name: 'crossed fingers', keywords: ['luck'], category: 'people' },
  { emoji: '🤟', name: 'love-you gesture', keywords: ['ily'], category: 'people' },
  { emoji: '🤘', name: 'sign of the horns', keywords: ['rock'], category: 'people' },
  { emoji: '👌', name: 'OK hand', keywords: ['ok'], category: 'people' },
  { emoji: '🫡', name: 'saluting face', keywords: ['salute'], category: 'people' },
  { emoji: '🫥', name: 'dotted line face', keywords: ['invisible'], category: 'people' },

  // Animals & Nature
  { emoji: '🐶', name: 'dog face', keywords: ['dog'], category: 'animals' },
  { emoji: '🐱', name: 'cat face', keywords: ['cat'], category: 'animals' },
  { emoji: '🐭', name: 'mouse face', keywords: ['mouse'], category: 'animals' },
  { emoji: '🐹', name: 'hamster', keywords: ['hamster'], category: 'animals' },
  { emoji: '🐰', name: 'rabbit face', keywords: ['bunny'], category: 'animals' },
  { emoji: '🦊', name: 'fox', keywords: ['fox'], category: 'animals' },
  { emoji: '🐻', name: 'bear', keywords: ['bear'], category: 'animals' },
  { emoji: '🐼', name: 'panda', keywords: ['panda'], category: 'animals' },
  { emoji: '🐨', name: 'koala', keywords: ['koala'], category: 'animals' },
  { emoji: '🐯', name: 'tiger face', keywords: ['tiger'], category: 'animals' },
  { emoji: '🦁', name: 'lion', keywords: ['lion'], category: 'animals' },
  { emoji: '🐮', name: 'cow face', keywords: ['cow'], category: 'animals' },
  { emoji: '🐷', name: 'pig face', keywords: ['pig'], category: 'animals' },
  { emoji: '🐸', name: 'frog', keywords: ['frog'], category: 'animals' },
  { emoji: '🐵', name: 'monkey face', keywords: ['monkey'], category: 'animals' },
  { emoji: '🙈', name: 'see-no-evil monkey', keywords: ['monkey'], category: 'animals' },
  { emoji: '🙉', name: 'hear-no-evil monkey', keywords: ['monkey'], category: 'animals' },
  { emoji: '🙊', name: 'speak-no-evil monkey', keywords: ['monkey'], category: 'animals' },
  { emoji: '🐔', name: 'chicken', keywords: ['chicken'], category: 'animals' },
  { emoji: '🐧', name: 'penguin', keywords: ['penguin'], category: 'animals' },
  { emoji: '🐦', name: 'bird', keywords: ['bird'], category: 'animals' },
  { emoji: '🦆', name: 'duck', keywords: ['duck'], category: 'animals' },
  { emoji: '🦉', name: 'owl', keywords: ['owl'], category: 'animals' },
  { emoji: '🐺', name: 'wolf', keywords: ['wolf'], category: 'animals' },
  { emoji: '🐗', name: 'boar', keywords: ['boar'], category: 'animals' },
  { emoji: '🐴', name: 'horse face', keywords: ['horse'], category: 'animals' },
  { emoji: '🦄', name: 'unicorn', keywords: ['unicorn'], category: 'animals' },
  { emoji: '🐝', name: 'honeybee', keywords: ['bee'], category: 'animals' },
  { emoji: '🦋', name: 'butterfly', keywords: ['butterfly'], category: 'animals' },
  { emoji: '🐢', name: 'turtle', keywords: ['turtle'], category: 'animals' },
  { emoji: '🐍', name: 'snake', keywords: ['snake'], category: 'animals' },
  { emoji: '🦖', name: 'T-Rex', keywords: ['dinosaur'], category: 'animals' },
  { emoji: '🦕', name: 'sauropod', keywords: ['dinosaur'], category: 'animals' },
  { emoji: '🐙', name: 'octopus', keywords: ['octopus'], category: 'animals' },
  { emoji: '🦈', name: 'shark', keywords: ['shark'], category: 'animals' },
  { emoji: '🐬', name: 'dolphin', keywords: ['dolphin'], category: 'animals' },
  { emoji: '🐳', name: 'spouting whale', keywords: ['whale'], category: 'animals' },
  { emoji: '🐠', name: 'tropical fish', keywords: ['fish'], category: 'animals' },
  { emoji: '🌸', name: 'cherry blossom', keywords: ['flower'], category: 'animals' },
  { emoji: '🌹', name: 'rose', keywords: ['flower', 'love'], category: 'animals' },
  { emoji: '🌻', name: 'sunflower', keywords: ['flower'], category: 'animals' },
  { emoji: '🌿', name: 'herb', keywords: ['plant'], category: 'animals' },
  { emoji: '🍀', name: 'four leaf clover', keywords: ['luck'], category: 'animals' },
  { emoji: '🌈', name: 'rainbow', keywords: ['pride', 'rainbow'], category: 'animals' },
  { emoji: '⭐', name: 'star', keywords: ['star'], category: 'animals' },
  { emoji: '🌙', name: 'crescent moon', keywords: ['night'], category: 'animals' },
  { emoji: '☀️', name: 'sun', keywords: ['day'], category: 'animals' },
  { emoji: '⚡', name: 'high voltage', keywords: ['zap'], category: 'animals' },
  { emoji: '🔥', name: 'fire', keywords: ['lit', 'hot'], category: 'animals' },

  // Food & Drink
  { emoji: '🍏', name: 'green apple', keywords: ['apple'], category: 'food' },
  { emoji: '🍎', name: 'red apple', keywords: ['apple'], category: 'food' },
  { emoji: '🍌', name: 'banana', keywords: ['banana'], category: 'food' },
  { emoji: '🍇', name: 'grapes', keywords: ['grapes'], category: 'food' },
  { emoji: '🍓', name: 'strawberry', keywords: ['berry'], category: 'food' },
  { emoji: '🍒', name: 'cherries', keywords: ['cherry'], category: 'food' },
  { emoji: '🍑', name: 'peach', keywords: ['peach'], category: 'food' },
  { emoji: '🍍', name: 'pineapple', keywords: ['pineapple'], category: 'food' },
  { emoji: '🥭', name: 'mango', keywords: ['mango'], category: 'food' },
  { emoji: '🍉', name: 'watermelon', keywords: ['melon'], category: 'food' },
  { emoji: '🍋', name: 'lemon', keywords: ['lemon'], category: 'food' },
  { emoji: '🥑', name: 'avocado', keywords: ['avocado'], category: 'food' },
  { emoji: '🍅', name: 'tomato', keywords: ['tomato'], category: 'food' },
  { emoji: '🥔', name: 'potato', keywords: ['potato'], category: 'food' },
  { emoji: '🥕', name: 'carrot', keywords: ['carrot'], category: 'food' },
  { emoji: '🌽', name: 'corn', keywords: ['corn'], category: 'food' },
  { emoji: '🍕', name: 'pizza', keywords: ['pizza'], category: 'food' },
  { emoji: '🍔', name: 'hamburger', keywords: ['burger'], category: 'food' },
  { emoji: '🌭', name: 'hot dog', keywords: ['hotdog'], category: 'food' },
  { emoji: '🥪', name: 'sandwich', keywords: ['sandwich'], category: 'food' },
  { emoji: '🌮', name: 'taco', keywords: ['taco'], category: 'food' },
  { emoji: '🌯', name: 'burrito', keywords: ['burrito'], category: 'food' },
  { emoji: '🍜', name: 'steaming bowl', keywords: ['ramen', 'noodles'], category: 'food' },
  { emoji: '🍣', name: 'sushi', keywords: ['sushi'], category: 'food' },
  { emoji: '🍰', name: 'shortcake', keywords: ['cake', 'dessert'], category: 'food' },
  { emoji: '🎂', name: 'birthday cake', keywords: ['birthday'], category: 'food' },
  { emoji: '🍪', name: 'cookie', keywords: ['cookie'], category: 'food' },
  { emoji: '🍫', name: 'chocolate bar', keywords: ['chocolate'], category: 'food' },
  { emoji: '🍿', name: 'popcorn', keywords: ['popcorn'], category: 'food' },
  { emoji: '☕', name: 'hot beverage', keywords: ['coffee', 'tea'], category: 'food' },
  { emoji: '🧋', name: 'bubble tea', keywords: ['boba'], category: 'food' },
  { emoji: '🍺', name: 'beer mug', keywords: ['beer'], category: 'food' },
  { emoji: '🥂', name: 'clinking glasses', keywords: ['cheers'], category: 'food' },

  // Activities
  { emoji: '🎉', name: 'party popper', keywords: ['party', 'celebrate'], category: 'activities' },
  { emoji: '🥳', name: 'partying face', keywords: ['party', 'celebrate'], category: 'activities' },
  { emoji: '🎊', name: 'confetti ball', keywords: ['party'], category: 'activities' },
  { emoji: '🎁', name: 'wrapped gift', keywords: ['gift'], category: 'activities' },
  { emoji: '🏆', name: 'trophy', keywords: ['win'], category: 'activities' },
  { emoji: '🥇', name: '1st place medal', keywords: ['win'], category: 'activities' },
  { emoji: '⚽', name: 'soccer ball', keywords: ['sports'], category: 'activities' },
  { emoji: '🏀', name: 'basketball', keywords: ['sports'], category: 'activities' },
  { emoji: '🏈', name: 'american football', keywords: ['sports'], category: 'activities' },
  { emoji: '🎮', name: 'video game', keywords: ['game'], category: 'activities' },
  { emoji: '🎲', name: 'game die', keywords: ['dice'], category: 'activities' },
  { emoji: '🎵', name: 'musical note', keywords: ['music'], category: 'activities' },
  { emoji: '🎶', name: 'musical notes', keywords: ['music'], category: 'activities' },
  { emoji: '🎨', name: 'artist palette', keywords: ['art'], category: 'activities' },

  // Travel & Places
  { emoji: '🚗', name: 'automobile', keywords: ['car'], category: 'travel' },
  { emoji: '🚕', name: 'taxi', keywords: ['taxi'], category: 'travel' },
  { emoji: '🚌', name: 'bus', keywords: ['bus'], category: 'travel' },
  { emoji: '🚆', name: 'train', keywords: ['train'], category: 'travel' },
  { emoji: '✈️', name: 'airplane', keywords: ['flight'], category: 'travel' },
  { emoji: '🚀', name: 'rocket', keywords: ['rocket', 'launch'], category: 'travel' },
  { emoji: '🛸', name: 'flying saucer', keywords: ['ufo'], category: 'travel' },
  { emoji: '⛵', name: 'sailboat', keywords: ['boat'], category: 'travel' },
  { emoji: '🗺️', name: 'world map', keywords: ['map'], category: 'travel' },
  { emoji: '🏝️', name: 'desert island', keywords: ['island'], category: 'travel' },
  { emoji: '🏔️', name: 'snow-capped mountain', keywords: ['mountain'], category: 'travel' },
  { emoji: '🏙️', name: 'cityscape', keywords: ['city'], category: 'travel' },

  // Objects
  { emoji: '💡', name: 'light bulb', keywords: ['idea'], category: 'objects' },
  { emoji: '🔒', name: 'locked', keywords: ['lock', 'secure'], category: 'objects' },
  { emoji: '🔑', name: 'key', keywords: ['key'], category: 'objects' },
  { emoji: '🧠', name: 'brain', keywords: ['brain'], category: 'objects' },
  { emoji: '💎', name: 'gem stone', keywords: ['diamond'], category: 'objects' },
  { emoji: '🪙', name: 'coin', keywords: ['coin', 'money'], category: 'objects' },
  { emoji: '💰', name: 'money bag', keywords: ['money'], category: 'objects' },
  { emoji: '📈', name: 'chart increasing', keywords: ['up', 'growth'], category: 'objects' },
  { emoji: '📉', name: 'chart decreasing', keywords: ['down'], category: 'objects' },
  { emoji: '📌', name: 'pushpin', keywords: ['pin'], category: 'objects' },
  { emoji: '📎', name: 'paperclip', keywords: ['clip'], category: 'objects' },
  { emoji: '📝', name: 'memo', keywords: ['note', 'write'], category: 'objects' },
  { emoji: '📣', name: 'megaphone', keywords: ['announce'], category: 'objects' },
  { emoji: '🔔', name: 'bell', keywords: ['notification'], category: 'objects' },
  { emoji: '🧰', name: 'toolbox', keywords: ['tools'], category: 'objects' },
  { emoji: '🛠️', name: 'hammer and wrench', keywords: ['tools', 'build'], category: 'objects' },
  { emoji: '⚙️', name: 'gear', keywords: ['settings'], category: 'objects' },
  { emoji: '💬', name: 'speech balloon', keywords: ['chat'], category: 'objects' },
  { emoji: '🗨️', name: 'left speech bubble', keywords: ['chat'], category: 'objects' },
  { emoji: '✉️', name: 'envelope', keywords: ['mail'], category: 'objects' },

  // Symbols
  { emoji: '✅', name: 'check mark button', keywords: ['check', 'yes'], category: 'symbols' },
  { emoji: '☑️', name: 'check box with check', keywords: ['check'], category: 'symbols' },
  { emoji: '❌', name: 'cross mark', keywords: ['no'], category: 'symbols' },
  { emoji: '⚠️', name: 'warning', keywords: ['warning'], category: 'symbols' },
  { emoji: '🚨', name: 'police car light', keywords: ['alert'], category: 'symbols' },
  { emoji: '💯', name: 'hundred points', keywords: ['100', 'perfect'], category: 'symbols' },
  { emoji: '❤️', name: 'red heart', keywords: ['love', 'heart'], category: 'symbols' },
  { emoji: '🧡', name: 'orange heart', keywords: ['heart'], category: 'symbols' },
  { emoji: '💛', name: 'yellow heart', keywords: ['heart'], category: 'symbols' },
  { emoji: '💚', name: 'green heart', keywords: ['heart'], category: 'symbols' },
  { emoji: '💙', name: 'blue heart', keywords: ['heart'], category: 'symbols' },
  { emoji: '💜', name: 'purple heart', keywords: ['heart'], category: 'symbols' },
  { emoji: '🖤', name: 'black heart', keywords: ['heart'], category: 'symbols' },
  { emoji: '🤍', name: 'white heart', keywords: ['heart'], category: 'symbols' },
  { emoji: '🔺', name: 'red triangle pointed up', keywords: ['up'], category: 'symbols' },
  { emoji: '🔻', name: 'red triangle pointed down', keywords: ['down'], category: 'symbols' },
  { emoji: '➡️', name: 'right arrow', keywords: ['arrow'], category: 'symbols' },
  { emoji: '⬅️', name: 'left arrow', keywords: ['arrow'], category: 'symbols' },
  { emoji: '⬆️', name: 'up arrow', keywords: ['arrow'], category: 'symbols' },
  { emoji: '⬇️', name: 'down arrow', keywords: ['arrow'], category: 'symbols' },

  // Flags (tiny starter set)
  { emoji: '🏳️', name: 'white flag', keywords: ['flag'], category: 'flags' },
  { emoji: '🏴', name: 'black flag', keywords: ['flag'], category: 'flags' },
  { emoji: '🏁', name: 'chequered flag', keywords: ['race'], category: 'flags' }
];

